"""create devices and loans tables

Revision ID: 8e88a3c46e3c
Revises: aa55df750f10
Create Date: 2026-09-25 18:52:07.423314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e88a3c46e3c'
down_revision: Union[str, Sequence[str], None] = 'aa55df750f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
    if "devices" not in existing_tables:
        op.create_table(
            "devices",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=150), nullable=False),
            sa.Column("serial_number", sa.String(length=100), nullable=False),
            sa.Column("device_type", sa.String(length=30), nullable=False),
            sa.Column("brand", sa.String(length=80), nullable=True),
            sa.Column("is_available", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.CheckConstraint(
                "device_type IN ('laptop', 'tablet', 'proyector', 'camara', 'router', 'monitor')",
                name="ck_devices_device_type",
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_devices_id", "devices", ["id"], unique=False)
        op.create_index(
            "ix_devices_serial_number", "devices", ["serial_number"], unique=True
        )

    existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
    if "loans" not in existing_tables:
        op.create_table(
            "loans",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("device_id", sa.Integer(), nullable=False),
            sa.Column("loan_date", sa.DateTime(timezone=True), nullable=False),
            sa.Column("return_date", sa.DateTime(timezone=True), nullable=True),
            sa.Column("status", sa.String(length=20), nullable=False),
            sa.CheckConstraint(
                "status IN ('active', 'returned', 'overdue')",
                name="ck_loans_status",
            ),
            sa.ForeignKeyConstraint(["device_id"], ["devices.id"]),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_loans_device_id", "loans", ["device_id"], unique=False)
        op.create_index("ix_loans_id", "loans", ["id"], unique=False)
        op.create_index("ix_loans_user_id", "loans", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_user_id'))
        batch_op.drop_index(batch_op.f('ix_loans_id'))
        batch_op.drop_index(batch_op.f('ix_loans_device_id'))

    op.drop_table('loans')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_serial_number'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))

    op.drop_table('devices')
    # ### end Alembic commands ###
